// Generated by mason - winkk_brick
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

part 'sentry_auth_provider.g.dart';

/// Automatically sets Sentry scope based on auth.
@Riverpod(keepAlive: true)
Future<void> sentryAuth(SentryAuthRef ref) async {
  //final auth = ref.watch(authProvider);
  throw UnimplementedError('TODO: Implement sentryAuth');

  await Sentry.configureScope((s) => s.setUser(SentryUser(
      id: 'TODO',
      email: 'TODO',
      name: 'TODO',
  )));
}