// Generated by mason - winkk_brick
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../features/home/home_page.dart';{{#homeWithBottomNav}}
import '../features/home/home_start.dart';{{/homeWithBottomNav}}

part 'routes.g.dart';

{{#homeWithBottomNav}}@TypedStatefulShellRoute<HomeShellRoute>(branches: [
  TypedStatefulShellBranch(routes: [
    TypedGoRoute<HomeRoute>(path: '/',),
  ]),
  TypedStatefulShellBranch(routes: [
    TypedGoRoute<NewShipmentRoute>(path: '/new-shipment'),
  ]),
  TypedStatefulShellBranch(routes: [
    TypedGoRoute<ExploreRoute>(path: '/explore'),
  ]),
  TypedStatefulShellBranch(routes: [
    TypedGoRoute<FriendsRoute>(path: '/friends'),
  ]),
  TypedStatefulShellBranch(routes: [
    TypedGoRoute<ProfileRoute>(path: '/profile'),
  ]),
])
class HomeShellRoute extends StatefulShellRouteData {
  const HomeShellRoute();
  @override
  Widget builder(context, state, navigationShell) {
    return HomePage(index: navigationShell.currentIndex, child: navigationShell);
  }
}

class HomeRoute extends GoRouteData {
  const HomeRoute();
  @override
  Widget build(context, state) => const HomeStart();
}

class NewShipmentRoute extends GoRouteData {
  const NewShipmentRoute();
  @override
  Widget build(context, state) => const Placeholder(color: Colors.blue);
}

class ExploreRoute extends GoRouteData {
  const ExploreRoute();
  @override
  Widget build(context, state) => const Placeholder(color: Colors.green);
}

class FriendsRoute extends GoRouteData {
  const FriendsRoute();
  @override
  Widget build(context, state) => const Placeholder(color: Colors.purple);
}

class ProfileRoute extends GoRouteData {
  const ProfileRoute();
  @override
  Widget build(context, state) => const Placeholder(color: Colors.orange);
}{{/homeWithBottomNav}}{{^homeWithBottomNav}}@TypedGoRoute<HomeRoute>(path: '/')
class HomeRoute extends GoRouteData {
  const HomeRoute();
  @override
  Widget build(context, state) => const HomePage();
}{{/homeWithBottomNav}}