// Generated by mason - winkk_brick
import 'package:flutter/material.dart';
import '../../utils/extensions/context_extensions.dart';

class ComingSoonAlert extends StatelessWidget {
  /// A simple alert dialog used as a placeholder in the app for features that are not yet implemented.
  /// 
  /// Can be used on any click handlers, buttons etc.
  const ComingSoonAlert({super.key});

  static show(BuildContext context) {
    showDialog(context: context, builder: (_) => const ComingSoonAlert());
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog.adaptive(
      title: const Text('Coming Soon', style: TextStyle(fontWeight: FontWeight.bold)),
      content: const Text('Dieses Feature wirds bald geben!'),
      actions: [
        TextButton(
          onPressed: () => context.navigator.pop(),
          child: const Text('winkk'),
        ),
      ],
    );
  }
}
