// Generated by mason - winkk_brick
import 'package:flutter/material.dart';

class ConditionalWrapper extends StatelessWidget {
  final bool condition;
  final Widget Function(Widget child) wrapper;
  final Widget Function(Widget child)? wrapperElse;
  final Widget child;

  /// A widget that conditionally wraps a [child] widget
  /// with a [wrapper] widget builder based on a [condition].
  /// Optionally a [wrapperElse] widget builder can be provided
  const ConditionalWrapper({
    super.key,
    required this.condition,
    required this.wrapper,
    required this.child,
    this.wrapperElse
  });

  @override
  Widget build(BuildContext context) {
    return condition ? wrapper(child) : child;
  }
}