// Generated by mason - winkk_brick
import 'package:device_info_plus/device_info_plus.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'device_info_provider.g.dart';

@Riverpod(keepAlive: true)
Future<BaseDeviceInfo> deviceInfo(DeviceInfoRef ref) async {
  final deviceInfoPlugin = DeviceInfoPlugin();
  return await deviceInfoPlugin.deviceInfo;
}