// Generated by mason - winkk_brick
import 'dart:async';
import 'dart:math';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../utils/extensions/riverpod_extensions.dart';

part 'dummy_provider.g.dart';

/// A provider that can be used as an example for timed caching and delayed loading.
@riverpod
Future<List<String>> dummy(DummyRef ref) async {
  await Future.delayed(Duration(seconds: 2));
  final fruits = ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'];
  fruits.shuffle(Random());
  ref.cacheAndInvalidateAfter(Duration(seconds: 15));
  return fruits;
}