// Generated by mason - winkk_brick
import 'package:flutter/foundation.dart';
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:responsive_framework/responsive_framework.dart';

/// General configuration values for the app
class ConfigValues {
  static const String appName = '{{appName}}';
  static const double minFontScaleFactor = 0.8;
  static const double maxFontScaleFactor = 1.3;
  static const String sentryDsn = '{{{sentryDsn}}}';

  static FlutterOptionsConfiguration sentryConfiguration = (options) {
    options.dsn = ConfigValues.sentryDsn;
    options.tracesSampleRate = 1.0;
    options.reportSilentFlutterErrors = true;
    options.environment = kReleaseMode ? 'prod' : 'dev';
  };

  /// Rudimentary breakpoints for responsive design
  static final List<Breakpoint> breakpoints = [
    Breakpoint(start: 0, end: 600, name: MOBILE),
    Breakpoint(start: 600, end: 1000, name: TABLET),
    Breakpoint(start: 1000, end: double.infinity, name: DESKTOP),
  ];
}