// Generated by mason - winkk_brick
import 'package:flutter/material.dart';

/// Durations used in animations, transitions etc.
class CustomDurations {
  static const Duration veryShort = Duration(milliseconds: 150);
  static const Duration short = Duration(milliseconds: 250);
  static const Duration medium = Duration(milliseconds: 400);
  static const Duration long = Duration(milliseconds: 600);
  static const Duration veryLong = Duration(milliseconds: 1000);
}