// Generated by mason - winkk_brick

/// Common sizes used across the app
class CustomSizes {
  static const double tiny = 4.0;
  static const double small = 8.0;
  static const double medium = 16.0;
  static const double mediumLarge = 20.0;
  static const double large = 24.0;
  static const double xlarge = 32.0;
  static const double xxlarge = 48.0;
  static const double xxxlarge = 64.0;
}