// Generated by mason - winkk_brick
import 'package:dio/dio.dart';

extension DioExtensions on Dio {
  /// Uses [get] and performs a [convert] function on the response data.
  Future<T> getAsType<T> (String path, T Function(dynamic e) convert, {Options? options, Object? data, Map<String, dynamic>? queryParameters}) async {
    final res = await get(
      path,
      options: options,
      data: data,
      queryParameters: queryParameters,
    );

    return convert(res.data!);
  }

  /// Uses [post] and performs a [convert] function on the response data.
  Future<T> postAsType<T> (String path, T Function(dynamic e) convert, {Options? options, Object? data, Map<String, dynamic>? queryParameters}) async {
    final res = await post(
      path,
      options: options,
      data: data,
      queryParameters: queryParameters,
    );

    return convert(res.data!);
  }
}