// Generated by mason - winkk_brick
import 'package:flutter/material.dart';

extension NavigatorExtensions on NavigatorState {
  /// Safe pop dialog that checks if a dialog is currently open before popping it.
  /// Avoids accidental popping of other pages.
  /// 
  /// Should be used when automatically popping dialogs, so there cannot be an accident where a page is popped instead of the dialog.
  void tryPopDialog(BuildContext context) {
    // Check if a dialog is currently open
    if (context.mounted && ModalRoute.of(context)?.isCurrent == true) {
      maybePop();
    }
  }
}