// Generated by mason - winkk_brick

/// Extension on Object to provide Kotlin-like extension functions
extension ObjectExtensions<T> on T {
  /// Executes the given function [op] and returns its result.
  R let<R>(R Function(T that) op) => op(this);

  /// Calls the specified function [op] with `this` value as its argument and returns `this` value.
  /// Useful for performing additional actions on an object.
  T also(void Function(T that) op) {
    op(this);
    return this;
  }
}