// Generated by mason - winkk_brick
import 'package:flutter/widgets.dart';

extension SliverExtensions on Widget {
  /// Convert a Widget to a Sliver with SliverToBoxAdapter
  SliverToBoxAdapter toSliver() {
    return SliverToBoxAdapter(
      child: this,
    );
  }
}