// Generated by mason - winkk_brick
import 'package:freezed_annotation/freezed_annotation.dart';

part 'preferences_model.freezed.dart';

@freezed
class PreferencesModel with _$PreferencesModel {
  const PreferencesModel._();

  const factory PreferencesModel({
    required bool temp, // Add your preferences here
  }) = _PreferencesModel;
}