// Generated by mason - winkk_brick
import 'package:flutter/material.dart';

class CustomTextStyles extends ThemeExtension<CustomTextStyles> {
  /// Global [TextTheme]s defining custom sizing and styles for text.
  static final globalTextTheme = TextTheme(
    displayLarge: TextStyle(),
    displayMedium: TextStyle(),
    displaySmall: TextStyle(),
    headlineLarge: TextStyle(),
    headlineMedium: TextStyle(), 
    headlineSmall: TextStyle(),
    titleLarge: TextStyle(),
    titleMedium: TextStyle(),
    titleSmall: TextStyle(),
    bodyLarge: TextStyle(),
    bodyMedium: TextStyle(),
    bodySmall: TextStyle(),
    labelLarge: TextStyle(), // For example buttons
    labelMedium: TextStyle(),
    labelSmall: TextStyle(),
  );

  /// Additional text styles not present in the [TextTheme].
  const CustomTextStyles({
    required this.temp,
  });

  final TextStyle temp; // Add your custom text styles here

  // Define sizing and styles, not colors.
  static const CustomTextStyles defaultTextStyles = CustomTextStyles(
    temp: TextStyle(
        fontSize: 24,
    )
  );

  // May modify [defaultTextStyles] to create a light theme.
  static const CustomTextStyles lightTextStyles = defaultTextStyles;

  // May modify [defaultTextStyles] to create a dark theme.
  static const CustomTextStyles darkTextStyles = lightTextStyles;

  static CustomTextStyles of(BuildContext context) => Theme.of(context).extension<CustomTextStyles>()!;

  @override
  ThemeExtension<CustomTextStyles> copyWith({
    TextStyle? temp,
  }) {
    return CustomTextStyles(
      temp: temp ?? this.temp,
    );
  }

  @override
  ThemeExtension<CustomTextStyles> lerp(covariant ThemeExtension<CustomTextStyles>? other, double t) {
    if (other is! CustomTextStyles) return this;
    return CustomTextStyles(
      temp: TextStyle.lerp(temp, other.temp, t)!,
    );
  }
}