// Generated by mason - winkk_brick
import 'package:flutter/material.dart';
 
class CustomColors extends ThemeExtension<CustomColors> {
  /// Global colors used across the app and in the theme
  static ColorScheme lightColorScheme = ColorScheme.fromSeed(
    seedColor: const Color({{themeColorSeed}}), // Main color
    brightness: Brightness.light,
  );

  {{^darkMode}}/*{{/darkMode}}static ColorScheme darkColorScheme = ColorScheme.fromSeed(
    seedColor: const Color({{themeColorSeed}}), // Main color
    brightness: Brightness.dark,
  );{{^darkMode}}*/{{/darkMode}}

  /// Additional colors not present in the ColorScheme
  const CustomColors({
    required this.temp,
  });

  final Color temp; /// Add your custom colors here

  static const CustomColors light = CustomColors(
    temp: Color(0xFF000000),
  );

  {{^darkMode}}/*{{/darkMode}}static const CustomColors dark = CustomColors(
    temp: Color(0xFFFFFFFF),
  );{{^darkMode}}*/{{/darkMode}}

  static CustomColors of(BuildContext context) => Theme.of(context).extension<CustomColors>()!;

  @override
  ThemeExtension<CustomColors> copyWith({
    Color? temp,
  }) {
    return CustomColors(
        temp: temp ?? this.temp,
    );
  }

  @override
  ThemeExtension<CustomColors> lerp(covariant ThemeExtension<CustomColors>? other, double t) {
    if (other is! CustomColors) return this;
    return CustomColors(
        temp: Color.lerp(temp, other.temp, t)!,
    );
  }
}

extension CustomColorExtension on Color {
  MaterialColor get materialColor {
    List strengths = <double>[.05];
    final swatch = <int, Color>{};
    final int r = red, g = green, b = blue;

    for (int i = 1; i < 10; i++) {
      strengths.add(0.1 * i);
    }
    for (var strength in strengths) {
      final double ds = 0.5 - strength;
      swatch[(strength * 1000).round()] = Color.fromRGBO(
        r + ((ds < 0 ? r : (255 - r)) * ds).round(),
        g + ((ds < 0 ? g : (255 - g)) * ds).round(),
        b + ((ds < 0 ? b : (255 - b)) * ds).round(),
        1,
      );
    }
    return MaterialColor(value, swatch);
  }

  Color get inverted {
    final r = 255 - red;
    final g = 255 - green;
    final b = 255 - blue;

    return Color.fromARGB((opacity * 255).round(), r, g, b);
  }
}