// Generated by mason - winkk_brick
import 'package:flutter/material.dart';
import '../utils/extensions/context_extensions.dart';
import '../values/custom_sizes.dart';

/// Common styles used across the app
class CustomStyles {
  static const Radius radiusOfBorder = Radius.circular(CustomSizes.small);
  static const BorderRadius borderRadius = BorderRadius.all(radiusOfBorder);
  static const BorderRadius iconOvalBorderRadius = BorderRadius.all(Radius.circular(CustomSizes.medium));

  static ButtonStyle secondaryButtonStyle(BuildContext context) =>
      FilledButton.styleFrom(backgroundColor: context.colorScheme.secondary);

  static ButtonStyle darkButtonStyle(BuildContext context) => FilledButton.styleFrom(
    backgroundColor: Colors.black,
    foregroundColor: Colors.white,
  );

  static const FontWeight thin = FontWeight.w100;
  static const FontWeight extraLight = FontWeight.w200;
  static const FontWeight light = FontWeight.w300;
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight semiBold = FontWeight.w600;
  static const FontWeight bold = FontWeight.w700;
  static const FontWeight extraBold = FontWeight.w800;
  static const FontWeight black = FontWeight.w900;
}