// Generated by mason - winkk_brick
import 'package:dio/dio.dart';
import 'package:native_dio_adapter/native_dio_adapter.dart' if (dart.library.html) 'fallback_adapter.dart';
import 'package:sentry_dio/sentry_dio.dart';

class DioBuilder {
  /// Builds a [Dio] instance with the default configurations.
  static Dio build(String userAgent) {
    final dio = Dio(BaseOptions(
      headers: {
        'User-Agent': userAgent,
      },
      followRedirects: false,
      connectTimeout: Duration(seconds: 5),
      receiveTimeout: Duration(seconds: 30),
    ));
    dio.httpClientAdapter = NativeAdapter();
    dio.addSentry();
    return dio;
  }
}