// Generated by mason - winkk_brick
import 'package:dio/dio.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../metadata/user_agent_provider.dart';
import 'dio_builder.dart';

part 'dio_provider.g.dart';

@riverpod
Dio dio(DioRef ref){
  final userAgent = ref.watch(userAgentProvider).requireValue;
  return DioBuilder.build(userAgent);
}