// Generated by mason - winkk_brick
import 'package:dio/dio.dart';
// ignore_for_file: non_constant_identifier_names

/// Fallback for [NativeAdapter] unsupported platforms.
/// Workaround to use in imports
HttpClientAdapter NativeAdapter({dynamic createCronetEngine, dynamic createCupertinoConfiguration}) => HttpClientAdapter();