// Generated by mason - winkk_brick
import 'package:universal_platform/universal_platform.dart';

/// Get a value based on the current platform. Supports Android, iOS, Windows, MacOS, Linux and Web.
T? getByPlatform<T>({
  T? android,
  T? ios,
  T? windows,
  T? macos,
  T? linux,
  T? web
}) {
  if (UniversalPlatform.isAndroid) {
    return android;
  } else if (UniversalPlatform.isIOS) {
    return ios;
  } else if (UniversalPlatform.isWindows) {
    return windows;
  } else if (UniversalPlatform.isMacOS) {
    return macos;
  } else if (UniversalPlatform.isLinux) {
    return linux;
  } else if (UniversalPlatform.isWeb) {
    return web;
  } else {
    return null;
  }
}